### ISSUE TITLE
Issue about getting pic from bebop2

### ISSUE THREAD

**Issue by wsywade** [N-Bz/bybop#4]
@N-Bz 
Hi,
We need a new function on bebop2 that we hope it could take a photo and transmit the photo to the controller side through Wi-Fi. However, I found that the bebop2 could only take photo and save it in the storage of the UAV. Is there a solution about this?
THX!

Shiyu

**Comment by N-Bz** [comment]
Hi,

This issue is not directly related to bybop, and such would be more suited for the official [developer forum](http://forum.developer.parrot.com/).

If you want to get back the pictures from the drone during flight, you'll have to download them by FTP.

The full process can be split into the following steps:
- **Take a picture**: send the [PictureV2](http://developer.parrot.com/docs/reference/bebop_2/#take-a-picture) command to the drone (in bybop this would be done with `drone.send_data('ardrone3', 'MediaRecord', 'PictureV2')`)
- **Wait for the drone answer**: The drone will send the [PictureTaken](http://developer.parrot.com/docs/reference/bebop_2/#picture-taken) event, hopefully with `taken` as its first argument (again, in bybop: `drone.wait_answer('ardrone3.MediaRecordEvent.PictureEventChanged')` to wait for the event (if necessary), then `success = (drone.get_state(copy=False).get_value('ardrone3.MediaRecordEvent.PictureEventChanged')['event'] == 0)`
- **Download the picture from the drone internal memory**: You can connect to the drone by FTP (port 21). All medias will be available in the `/internal_000/Bebop_2/media/` folder, with the following name pattern: `Drone_Model_Year-Month-DayTHourMinutesSeconds+Timezone_FlightId.jpg` where the flight id part is optional (i.e. name can be `Bebop_2_2017-04-06T095047+0000_XXXXXX.jpg` if the picture was taken during a flight or a recording  or `Bebop_2_2017-04-06T095047+0000_.jpg` otherwise)

All ftp-related parts won't be integrated into bybop (you can do it with other tools)

**Comment by wsywade** [comment]
Thanks for your reply! Really helpful to me!
